# Generated by Django 4.2.16 on 2024-11-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure_Design', '0003_alter_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='characteristic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='employer_opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='illustration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
