# Generated by Django 4.2.11 on 2025-01-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbannermodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='min_description1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='min_description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='min_description3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='mini_title1',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='mini_title2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimbannermodel',
            name='mini_title3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
