# Generated by Django 4.2.11 on 2025-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0002_bimbannermodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimbannermodel',
            name='image_title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
