# Generated by Django 4.2.11 on 2025-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0003_bimbannermodel_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimPanelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='bim/banner')),
                ('image_title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('mini_title1', models.CharField(max_length=1000)),
                ('mini_title2', models.CharField(max_length=1000)),
                ('mini_title3', models.CharField(max_length=1000)),
                ('mini_description1', models.TextField()),
                ('mini_description2', models.TextField()),
                ('mini_description3', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BimBannerModel',
        ),
        migrations.AddField(
            model_name='bimcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='bim/category'),
            preserve_default=False,
        ),
    ]
