# Generated by Django 4.2.11 on 2025-01-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BIM', '0005_bimtraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimpanelmodel',
            name='project_base_title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimpanelmodel',
            name='slider1_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimpanelmodel',
            name='slider2_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bimpanelmodel',
            name='slider3_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
