# Generated by Django 4.2.16 on 2024-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='image',
            field=models.ImageField(upload_to='media/image/coworking'),
        ),
    ]
