# Generated by Django 4.2.11 on 2024-11-26 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_coworking_characteristic_coworking_coworker_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
