# Generated by Django 4.2.11 on 2024-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_Area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
