# Generated by Django 4.2.11 on 2024-11-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_project_total_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gravity_loading_sys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lateral_loading_sys',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
