# Generated by Django 4.2.11 on 2024-11-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='image/project/'),
        ),
    ]
